### ISSUE TITLE
TypeError: Cannot explicitly set an encoding with a unicode string

### ISSUE THREAD

**Issue by maxart** [operasoftware/oex2nex#1]
Hi,

I have tried converting one of my extensions ( https://addons.opera.com/en/extensions/details/dribbbly/ ), but I am getting the following error: "TypeError: Cannot explicitly set an encoding with a unicode string"

---

Here's the full dump:

max:oex2nex max$ python oex2nex/convertor.py -xd ~/Downloads/dribbbly-1.3-1.oex ~/Downloads/
Reading oex file.
('Oex:', <zipfile.ZipFile instance at 0x108aa47a0>, ', Nex:', <zipfile.ZipFile instance at 0x108aa4758>)
('Config.xml', u'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<widget xmlns="http://www.w3.org/ns/widgets" id="https://addons.opera.com/addons/extensions/details/dribbbly/" version="1.3" href="https://addons.opera.com/extensions/details/dribbbly/">\n  <name>Dribbbly</name>\n  <icon src="icons/icon48.png"/>\n  <access origin="*"/>\n  <license>Copyright 2011 maxart. All rights reserved.</license>\n  <author href="http://twitter.com/#!/maxart" email="max@maxart.me">maxart</author>\n  <update-description href="https://extension-updates.opera.com/api/w3c-wd1/update/6063e235-2f51-46d8-8917-fc20ffe11431/"/>\n  <description xml:lang="en">A simple Dribbble viewer for Opera</description>\n</widget>\n')
('Access origins:', [['*', 'false']])
('Feature names: ', [])
('Preferences: ', {})
('Icon files: ', {'128': 'icons/icon48.png'})
('Author name: ', 'maxart')
('Author URL: ', 'http://twitter.com/#!/maxart')
Handling file: config.xml
Handling file: icons/icon16.png
Handling file: icons/icon48.png
Handling file: index.html
Traceback (most recent call last):
  File "oex2nex/convertor.py", line 1049, in <module>
    main()
  File "oex2nex/convertor.py", line 1041, in main
    convertor.convert()
  File "oex2nex/convertor.py", line 681, in convert
    self._convert()
  File "oex2nex/convertor.py", line 391, in _convert
    file_data = shim_wrap(file_data, "index", prefstore)
  File "oex2nex/convertor.py", line 716, in _shim_wrap
    doc = htmlparser.parse(html, "utf-8")
  File "build/bdist.macosx-10.8-intel/egg/html5lib/html5parser.py", line 223, in parse
  File "build/bdist.macosx-10.8-intel/egg/html5lib/html5parser.py", line 87, in _parse
  File "build/bdist.macosx-10.8-intel/egg/html5lib/tokenizer.py", line 40, in __init__
  File "build/bdist.macosx-10.8-intel/egg/html5lib/inputstream.py", line 128, in HTMLInputStream
TypeError: Cannot explicitly set an encoding with a unicode string

---

![screen shot 2013-05-28 at 2 48 27 pm](https://f.cloud.github.com/assets/34616/571140/b47d73a0-c76d-11e2-8801-54ee78e15780.png)

**Comment by miketaylr** [comment]
Hey @maxart, thanks for the issue! Hari committed a fix in a branch here, https://github.com/operasoftware/oex2nex/commit/b43a3bebbd431a84a339b5ca0453ff04aca9928f. Do you think you could give it a spin? Make sure you're on the html5-unicode-whatever-the-branch-is-actually-called branch. 

Let me know if you need any help with that. :)

Or, can you host your extension somewhere so we can do the same?

**Comment by maxart** [comment]
Hey @miketaylr that did the trick, nice work!

Don't know if it's related to the conversion, but I am getting an error when trying to load the generated .nex into Opera Next:
"Extension installation failed. Package is invalid: 'CRX_MAGIC_NUMBER_INVALID'."

**Comment by miketaylr** [comment]
@maxart yeah, I guess that's expected (and poorly documented perhaps). If you give the convertor tool a .pem file to sign the extension, then it will work. Otherwise you need to load it as an Unpacked Extension through the extensions manager. You can get a converted unzipped folder by passing the `-x` flag.

Unless it's a bug. :)

**Comment by maxart** [comment]
Awesome, thanks! :D
Loading the folder as Unpacked Extension worked. All good ;)
Now to fight with the API changes, and make things work again.

**Comment by miketaylr** [comment]
Cool! Just need to do a little more regression testing before merging the branch. And I guess make the README more obvious.
